#!/usr/bin/env python3

import math
import pdb
import pprint
import sys

class Grid(list):
    def __init__(self, id=None):
        self._id = id
        self._map = []
        self._visited = set()
        super().__init__(self)

    def __repr__(self):
        return f"Grid{str(self._id)}"

    def pprint(self):
        for row in self:
            print(''.join([f"{x:02d}" for x in row]))

    def startnode(self):
        for row in self:
            for height in row:
                if height == 0:
                    return (self.index(row),row.index(height))

    def baddfsmap(self, node):
        if node not in self._visited:
            self._visited.add(node)
            self._map.insert(0,node)
            (row,col) = node
            height = self[row][col]
            print(f"map{row,col} {height:02d} {self._map}")
            if height == 27:
                #yield self._map
                return self._map
            ### Include diagonals
            #for (nextr,nextc) in ((row-1,col-1), (row-1,col), (row-1,col+1), (row,col-1), (row,col+1), (row+1,col-1), (row+1,col), (row+1,col+1)):
            ### Up,Down,Left,Right
            for (nextr,nextc) in ((row,col-1), (row-1,col), (row,col+1), (row+1,col)):
                if (nextr,nextc) not in self._visited \
                   and nextr >= 0 \
                   and nextr < len(self) \
                   and nextc >= 0 \
                   and nextc < len(self[nextr]) \
                   and self[nextr][nextc] <= height + 1:
                    nextnode = self.map((nextr,nextc))
                    return nextnode
                    #yield from self.map((nextr,nextc))
                    #return self.map((nextr,nextc))
                    
    ### Who can remember what I was trying here... not me                
    def unknownmap(self, node):
        stack = [(node, [node])]
        while stack:
            (node,path) = stack.pop(0)
            (row,col) = node
            height = self[row][col]
            print(f"map{row,col} {height:02d} lenm{len(self._map)} lenp{len(path)} {path}")
            ### Up,Down,Left,Right
            for (nextr,nextc) in ((row,col-1), (row-1,col), (row,col+1), (row+1,col)):
                if (nextr,nextc) not in path \
                   and nextr >= 0 \
                   and nextr < len(self) \
                   and nextc >= 0 \
                   and nextc < len(self[nextr]) \
                   and self[nextr][nextc] <= height + 1:
                    #print(f"map{nextr,nextc} {self[nextr][nextc]:02d} {path}")
                    path = path + [(nextr,nextc)]
                    if self[nextr][nextc] == 27:
                        #yield path + [(nextr,nextc)]
                        print(f"map{nextr,nextc} {height:02d} lenm{len(self._map)} lenp{len(path)}")
                        if not self._map or len(path) <= len(self._map):
                            self._map = path
                    else:
                        stack.append(((nextr,nextc), path))
        return self._map

    ### Funcional BFS but limited to small data sets
    def map(self, node):
        q = [(node, [node])]
        while q and not self._map:
            (node,path) = q.pop(0)
            self._visited.add(node)
            (row,col) = node
            height = self[row][col]
            #print(f"map{row,col} {height:02d} lenp{len(path)} {path}")
            print(f"map{row,col} {height:02d} lenp{len(path)}")
            ### Up,Down,Left,Right
            for (nextr,nextc) in ((row,col-1), (row-1,col), (row,col+1), (row+1,col)):
                if (nextr,nextc) not in self._visited \
                   and (nextr,nextc) not in path \
                   and nextr >= 0 \
                   and nextr < len(self) \
                   and nextc >= 0 \
                   and nextc < len(self[nextr]) \
                   and self[nextr][nextc] <= height + 1:
                    ### path needs to be distinct per child, not additive 
                    nextpath = path + [(nextr,nextc)]
                    if self[nextr][nextc] == 27:
                        if not self._map:
                            self._map = nextpath
                        return nextpath
                    else:
                        q.append(((nextr,nextc),nextpath))
                        
    def printmap(self):
        print(' '.join([f"{r,c}" for (r,c) in self._map]))
        print(f"steps[{len(self._map)-1}]")

def main():
    filename = "input.txt"
    if (len(sys.argv) > 1 and sys.argv[1] == "test"):
        filename = "test.txt"
        knots = 1
    if (len(sys.argv) > 1 and sys.argv[1] == "test2"):
        filename = "test2.txt"
    f = open(filename,"r")

    grid = Grid(0)
    for line in f.readlines():
        row = []
        line = line.rstrip('\n')
        for token in list(line):
            height = None
            if token == 'S':
                height = 0
            elif token == 'E':
                height = 27
            else:
                height = ord(token) - 96
            row.append(height)
        grid.append(row)
    grid.pprint()
    grid.map(grid.startnode())
    #grid.badbfsmap(grid.startnode())
    #grid._map = list(grid.badbfsmap(grid.startnode()))
    grid.printmap()

if __name__ == "__main__":
    main()