#!/usr/bin/env python3

def rangeset(rangestring):
    (begin,end) = rangestring.split('-')
    return set(range(int(begin),int(end)+1))
    
def is_either_subset(a,b):
    retval = 0
    if a <= b or a >= b:
        retval = 1
    return retval
    
def is_overlap(a,b):
    retval = 0
    if len(a & b):
        retval = 1
    return retval

def main():
    f = open("input.txt","r")
    subsets = 0
    overlaps = 0
    for line in f.readlines():
        line = line.strip()
        (a,b) = line.split(',')
        seta = rangeset(a)
        setb = rangeset(b)
        subsets += is_either_subset(seta,setb)
        overlaps += is_overlap(seta,setb)
        print(f"subsets[{subsets}] overlaps[{overlaps}] a[{a}] b[{b}] subset[{is_either_subset(seta,setb)}] overlap[{is_overlap(seta,setb)}]")
    print(f"subsets[{subsets}] overlaps[{overlaps}]")

if __name__ == "__main__":
    main()