#!/usr/bin/env python3

import math
import pdb
import pprint
import sys

class Monkey:
    def __init__(self, id=None, items=[], op=None, test=None, next_true=None, next_false=None):
        self.id = id
        self.items = items
        self.op = op
        self.test = test
        self.next_true = next_true
        self.next_false = next_false
        self.inspected = 0

    def __repr__(self):
        return f"Monkey{str(self.id)} inspected[{self.inspected}] items[{','.join([str(x) for x in self.items])}]"
        
    def play(self, monkeys):
        self.items.reverse()
        while self.items:
            item = self.items.pop()
            ### inspect: perform op
            new_item = self.op(item)
            self.inspected += 1
            ### reduce worry: / 3 round down
            new_item = math.floor(new_item / 3)
            ### update item value
            #self.items[self.items.index(item)] = new_item
            ### test: perform test
            if self.test(new_item):
                ### toss: test result sends item to other monkey
                monkeys[self.next_true].items.append(new_item)
                #print(monkeys[self.next_true])
            else:
                ### toss: test result sends item to other monkey
                monkeys[self.next_false].items.append(new_item)
                #print(monkeys[self.next_false])

def main():
    filename = "input.txt"
    if (len(sys.argv) > 1 and sys.argv[1] == "test"):
        filename = "test.txt"
    if (len(sys.argv) > 1 and sys.argv[1] == "test2"):
        filename = "test2.txt"
    f = open(filename,"r")
    
    #for line in f.readlines():
    #    line = line.rstrip('\n')
    #print(f"input[{input}]")
    
    monkeys = [ \
              Monkey(id=0, items=[54,61,97,63,74], op=lambda x: x*7, test=lambda x: x%17==0, next_true=5, next_false=3), \
              Monkey(id=1, items=[61,70,97,64,99,83,52,87], op=lambda x: x+8, test=lambda x: x%2==0, next_true=7, next_false=6), \
              Monkey(id=2, items=[60,67,80,65], op=lambda x: x*13, test=lambda x: x%5==0, next_true=1, next_false=6), \
              Monkey(id=3, items=[61,70,76,69,82,56], op=lambda x: x+7, test=lambda x: x%3==0, next_true=5, next_false=2), \
              Monkey(id=4, items=[79,98], op=lambda x: x+2, test=lambda x: x%7==0, next_true=0, next_false=3), \
              Monkey(id=5, items=[72,79,55], op=lambda x: x+1, test=lambda x: x%13==0, next_true=2, next_false=1), \
              Monkey(id=6, items=[63], op=lambda x: x+4, test=lambda x: x%19==0, next_true=7, next_false=4), \
              Monkey(id=7, items=[72,51,93,63,80,86,81], op=lambda x: x*x, test=lambda x: x%11==0, next_true=0, next_false=4), \
              ]
    print("init")
    items = 0
    for monkey in monkeys:
        print(monkey)
        items += len(monkey.items)
    print(f"total items: {items}")
    print()
    for round in range(0,20):
        items = 0
        print(f"round[{round}]")
        for monkey in monkeys:
            monkey.play(monkeys)
        for monkey in monkeys:
            print(monkey)
            items += len(monkey.items)
        print(f"total items: {items}")
        print()

if __name__ == "__main__":
    main()