#!/usr/bin/env python3

import pprint

class Position:
    def __init__(self, x=0, y=0)
    self.x = x
    self.y = y
    
    def pos(self):
        return (self.x,self.y)
        
class H(Position):
    def travel(self,dir,mag):
        if dir == "U":
            self.y += mag
        elif dir == "D":
            self.y -= mag
        elif dir == "R":
            self.x += mag
        elif dir == "L":
            self.x -= mag
        return self.pos()

class T(Position):
    def __init__(self, x=0, y=0)
    self.x = x
    self.y = y
    
    def follow(self,h):
           
def printgrid(grid):
    for row in grid:
        print(''.join([str(x) for x in row]))
    
def main():
    filename = "input.txt"
    if (sys.args[0] == "test"):
        filename = "test.txt"
    f = open(filename,"r")
    
    h = new H()
    t = new T()
    visited = { t }
    for line in f.readlines():
        line = line.rstrip('\n')
        (dir,mag) = line.split(' ')
        mag = int(mag)
        
    
    #print(f"visible[{visible}] bestview[{bestview}]")
    

if __name__ == "__main__":
    main()