#!/usr/bin/env python3

import math
import pprint
import sys

class Position:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
    
    def pos(self):
        return (self.x,self.y)
        
class H(Position):
    def __init__(self, x=0, y=0):
        super().__init__(x, y)
        self.t = T(x=self.x, y=self.y)

    def travel(self,dir,mag):
        if dir == "U":
            self.y += mag
        elif dir == "D":
            self.y -= mag
        elif dir == "R":
            self.x += mag
        elif dir == "L":
            self.x -= mag
        self.t.follow(self)        
        return self.pos()

class T(Position):
    def __init__(self, x=0, y=0):
        super().__init__(x,y)
        self.visited = { self.pos() }
    
    def follow(self,h):
        dx = h.x - self.x
        dy = h.y - self.y
        ### move up or down
        if self.x == h.x and self.y != h.y and abs(dy) >= 2:
            self.y += int(math.copysign(1,dy))
        ### move left or right
        elif self.x != h.x and self.y == h.y and abs(dx) >= 2:
            self.x += int(math.copysign(1,dx))
        ### move diagonal if not in alignment and > 2 difference
        if self.x != h.x and self.y != h.y and (abs(dx) >=2 or abs(dy) >= 2):
            self.x += int(math.copysign(1,dx))
            self.y += int(math.copysign(1,dy))
        self.visited.add(self.pos())
           
def printgrid(points):
    print(''.join([str(x) for x in points]))
    
def main():
    filename = "input.txt"
    if (len(sys.argv) > 1 and sys.argv[1] == "test"):
        filename = "test.txt"
    f = open(filename,"r")
    
    h = H()
    #print(f"h[{h.pos()}] t[{h.t.pos()}] v[{h.t.visited}]")
    for line in f.readlines():
        line = line.rstrip('\n')
        (dir,mag) = line.split(' ')
        mag = int(mag)
        for i in range(0,mag):
            h.travel(dir,1)
        #print(f"h[{h.pos()}] t[{h.t.pos()}] v[{h.t.visited}]")
    print(f"visited[{h.t.visited}]")
    print(f"visited[{len(h.t.visited)}]")
    

if __name__ == "__main__":
    main()