#!/usr/bin/env python3

def main():
    f = open("input.txt","r")
    frame = []
    for line in f.readlines():
        line = line.rstrip('\n')
        chars = list(line)
        for i in range(len(chars)):
            current = chars[i]
            frame.append(current)
            if len(frame) > 14:
                frame = frame[1:]
            if len(set(frame)) == 14:
                print(f"i[{i}] frame[{frame}] current[{current}]")
                break

if __name__ == "__main__":
    main()